### PR TITLE
CAT-70 fixed error message in console

### PR DESCRIPTION
**Pull request by pablitomilenio**

### CODE REVIEW

**Comment by BeatrizRCorreia** [comment]
Hello Pablo, if you check the files changed by this pull request, you will notice that this code was already changed in your last commit to the main branch (https://github.com/med-united/connector-admin.med-united.health/commit/7746601384cf7109b7ec9a5fd0ea9f12ea3d2c21).
So you can delete this branch and this pull request :heavy_check_mark:

**Comment by pablitomilenio** [comment]
Hello @BeatrizRCorreia 
if (sNextLayout == null) sNextLayout = "MidColumnFullScreen";
I need this line for the warning message to be fixed.

**Comment by BeatrizRCorreia** [comment]
Hello @pablitomilenio, I did not notice that line, thanks for letting me know. Then you don't need to open a pull request, you can do a commit directly to the main branch with the ticket number as usual and delete this pull request and branch.

This way we keep our commit history more clean because we avoid adding 3 commits :)

**Review by ruszkipista — APPROVED** [review]
no issues

**Comment by BeatrizRCorreia** [comment]
Hello @ruszkipista and Hello @pablitomilenio, as the lead in this project I am trying to coordinate it in the best way. In this case, I told you that we shouldn't add 3 commits to change one line and instead do a direct commit to the main branch to keep our commit history clean. You don't agree with me?

**Pull request merged**
